apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
 name: app-front # Название Pod
 labels: # Метки в формате key: value
   key: value
spec: # Описание Pod
 containers: # Описание контейнеров внутри Pod
 - name: app-front # Название контейнера
   image: devopscourses/otus:frontend.v1 # Образ из которого создается контейне
   volumeMounts:
   - name: app
     mountPath: /app
 initContainers:
 - name: init
   image: busybox:1.34.1
   volumeMounts:
   - name: app
     mountPath: /app
   command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
 volumes:
   - name: app
     emptyDir: {}
